FirebaseError: The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/newv2-68c50/firestore/indexes?create_composite=Cklwcm9qZWN0cy9uZXd2Mi02OGM1MC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdXNlcnMvaW5kZXhlcy9fEAEaDgoKdG90YWxTY29yZRACGhQKEHF1aXp6ZXNDb21wbGV0ZWQQAhoMCghfX25hbWVfXxACn FirebaseError: The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/newv2-68c50/firestore/indexes?create_composite=Ck9wcm9qZWN0cy9uZXd2Mi02OGM1MC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvYWN0aXZpdHlMb2cvaW5kZXhlcy9fEAEaBwoDdWlkEAEaDQoJdGltZXN0YW1wEAEaDAoIX19uYW1lX18QAQ ...fix these two issues